-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKDWMuWkTxeUfBjhJ
JV6usaHY1WXEL1slNu33ZDlygtOgCgYIKoZIzj0DAQehRANCAATeox1zg6Z1KnEk
pfBlQBSsaA+HqTYSdGQvmakex1HnFmVo6PLA4i6lfnktgQ0T3RjxWq2cNHhr49rP
MqkxYVAF
-----END PRIVATE KEY-----