on:
  push:
    branches:
      - main
jobs:
  deploy_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup ruby
        run: brew install openssl readline rbenv ruby-build

      - name: Install npm dependencies
        run: |
          npm install && npx react-native unlink react-native-vector-icons

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh

      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh

      - name: setup fastlane
        run: cd ios && bundle install

      - name: setup xcode version
        run: |
          cd ios
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: upload to testflight
        env:
          FASTLANE_USER: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          FASTLANE_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          cd ios
          bundle exec fastlane beta
